### ISSUE TITLE
Re-Rolling Optimized Villagers

### ISSUE THREAD

**Issue by PugglesLesser** [RebelMythik/AntiVillagerLag#26]
**Is your feature request related to a problem? Please describe.**
Villagers can't re-roll when under Optimize, which is the entire point of the plugin I fully understand, but I have a small solution that might be neat to see configurable.

**Describe the solution you'd like**
Possibly a command such as /rollvillager or /roll or something similar, or a certain item you can use to immediately re-roll the villager and randomize its trades. This would be disable-able in the config for players who don't want it.

**Additional context**
My server uses a custom enchanting system that adds a ton of new enchantments to the game, so people use tons and tons of villagers to get them in a reasonable way. The process to get the villagers typically involves re-rolling librarians until they give the deal you want. This command might remove some of the work needed to get them, so maybe a configurable exp cost, or item cost to use the command, or something similar.

**Comment by D-VR** [comment]
hmh In my opinion, this is a little too specific and goes beyond the intention of this plug-in, since you can still reroll villagers by destroying their workstation and then disabling / enabling optimization.

(and adding a reroll command would take away the vanilla way/ gameplay of doing it)

There is a radius command in the works which would allow users to mass disable/ enable villagers around them, which would ease that step a lot. (and you can disable cooldown so they don't have to wait in between)

**Comment by RebelMythik** [comment]
Hey thanks for making a feature request! Unfortunately this would be a pretty hacky feature. Would be best to just reroll villagers manually.
